# Lightening up the mood
# Print a random, hopefully interesting, adage.

if (( $+commands[fortune] )); then
  alias login_fortune="fortune $HOME/.groundzero/configs/common/files/fortune"
  PIPE1="cat"
  PIPE2="cat"

  # if (($+commands[cowsay])); then
  #   # PIPE1="cowsay -f ~/.groundzero/configs/common/files/cowsay/blank.cow"
  #   PIPE1="cowsay"
  # fi
  if (($+commands[lolcat])); then
    PIPE2='lolcat'
  fi

  if [[ -t 0 || -t 1 ]]; then
    export FORTUNE="`login_fortune`"
    echo $FORTUNE | eval "$PIPE1" | eval "$PIPE2"
  fi
fi
