# Lightening up the mood
# Print a random, hopefully interesting, adage.

if (( $+commands[fortune] )); then
  PIPE1="cat"
  PIPE2="cat"

  # DISABLED TILL I FIND A RELIABLE WAY TO INTSALL COWFILES
  # if (($+commands[cowsay])); then
  #   PIPE1="cowsay -f blank"
  # fi
  if (($+commands[lolcat])); then
    PIPE2='lolcat'
  fi

  if [[ -t 0 || -t 1 ]]; then
    export FORTUNE="`fortune`"
    echo $FORTUNE | $PIPE1 | eval "$PIPE2"
  fi
fi
